apiVersion: apps/v1
kind: Deployment
metadata:
  name: platesearcher
  labels:
    app: platesearcher

spec:
  replicas: 2
  selector:
    matchLabels:
      app: platesearcher
  strategy:
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: platesearcher
    spec:
      containers:
        - image: hub.docker.com/vanthios/platesearcher:latest
          name: platesearcher-service
          ports:
            - containerPort: 3030
              name: rest-api