apiVersion: apps/v1
kind: Deployment
metadata:
  name: platesearcher-api
  namespace: platesearcher
  labels:
    app: platesearcher-api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: platesearcher-api
  strategy:
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: platesearcher-api
    spec:
      containers:
        - image: vanthios/platesearcher
          name: platesearcher-api
          ports:
            - containerPort: 3500
              name: rest-api